name: Raspagem e Notificação Automática

on:
  schedule:
    - cron: '0 7 * * *'  # Executa todos os dias às 07:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Atualizado para a versão mais recente

    - name: Set up Python
      uses: actions/setup-python@v4  # Atualizado para a versão mais recente
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create credentials file
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > credentials.json
      shell: bash

    - name: Execute script
      run: python RASPAGEMDOU.py
      env:
        EMAIL: ${{ secrets.EMAIL }}
        SENHA_EMAIL: ${{ secrets.SENHA_EMAIL }}
        PLANILHA: ${{ secrets.PLANILHA }}
        DESTINATARIOS: ${{ secrets.DESTINATARIOS }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json
